### ISSUE TITLE
Is it a good idea?

### ISSUE THREAD

**Issue by 1995parham** [1995parham/Awesome-Fibonacci#1]
Do you think its good Idea to implement Fibonacci in different languages and algorithms here?

**Comment by Tabrizian** [comment]
Inspired from awesome hello world ? :)))

**Comment by 1995parham** [comment]
Yes :joy:

**Comment by Tabrizian** [comment]
Maybe if we can advertise it broadly it becomes trending repository on GitHub but I can't think of any use case for it.

**Comment by 1995parham** [comment]
Me too 😂 👍 😂
