### ISSUE TITLE
غایت از ایجاد این رپو

### ISSUE THREAD

**Issue by mmsamiei** [1995parham/Awesome-Fibonacci#2]
سلام علیکم
بنده یک سوال داشتم که هدف و غایت از ایجاد این رپو چیه؟

**Comment by pi0** [comment]
<div dir=rtl>
با سلام

فکر می‌کنم مقصود اصلی پرورش مهارت های پروگرامینگ و  آشنایی برنامه نویسان با زبان های گوناگون از طریق نوشتن کد فیبوناچی بوده است.
</div>

**Comment by 1995parham** [comment]
من حمایت خودم از دلیل پویا را اعلام می‌کنم :دی
